### ISSUE TITLE
NoMethod error in fork_supervisor upon terminating processes

### ISSUE THREAD

**Issue by Darhazer** [rails/solid_queue#305]
Since we upgraded to 0.6.0 our error reporting system started producing:
```
Undefined method `>' for nil (NoMethodError)

          if (terminated_fork = forks.delete(pid)) && !status.exited? || status.exitstatus > 0
```

The code was introduced in https://github.com/rails/solid_queue/pull/277

I suppose the code is meant to be

```ruby
if (terminated_fork = forks.delete(pid)) && (!status.exited? || status.exitstatus > 0)
```

**Comment by rosa** [comment]
Oh, yes, indeed! Do you want to open a PR with that change? 

We haven't run into this error, and I didn't notice it in different tests...  I think it's because in all my tests, a `terminated_fork` is found, and either `status.exited?` is `false`, so `status.exitstatus` is not evaluated, or `status.exited?` is `true` and then `status.exitstatus` is present. 

I imagine you're running into this error because in your case `forks.delete(pid)` returns `nil`. But I'm not sure how that could happen 😕 How can you have a child process that was forked without having the `pid` tracked? 😕  Do you have more details on where you're getting this error?

**Comment by Darhazer** [comment]
I don't know how and why this is happening, and since I don't know how to reproduce it and how to write a test for it, I didn't submit a PR. So if I figure out how to reproduce it at least in a test, I'm happy to open PR. Any tips?

All I can say is we are using Heroku and we started getting the above mentioned error in Sentry

**Comment by rosa** [comment]
No worries, I'll take care of it. I'm not sure how to write a test for this either right now as I don't know how it can happen 😅

**Comment by rosa** [comment]
This one should be fixed now as part of https://github.com/rails/solid_queue/pull/308, and shipped in version 0.7.0.

**Comment by Darhazer** [comment]
Thank you, @rosa
